"""AES3 cross-TF hierarchy vocabulary — relations and hierarchy states only."""

from __future__ import annotations

from typing import FrozenSet

# Adjacent pairs (child → parent).
PAIR_CHAIN: tuple[tuple[str, str], ...] = (
    ("M15", "M30"),
    ("M30", "H1"),
    ("H1", "H4"),
)

TF_SENIORITY: tuple[str, ...] = ("M15", "M30", "H1", "H4")

# Propagation direction — structural hierarchy, NOT price direction.
PROP_NONE = "NONE"
PROP_TOWARD_HIGHER_TF = "TOWARD_HIGHER_TF"
PROP_TOWARD_LOWER_TF = "TOWARD_LOWER_TF"
PROP_MIXED = "MIXED"

PROPAGATION_DIRECTIONS: FrozenSet[str] = frozenset(
    {PROP_NONE, PROP_TOWARD_HIGHER_TF, PROP_TOWARD_LOWER_TF, PROP_MIXED}
)

# Pair relation states.
REL_UNRESOLVED = "UNRESOLVED_RELATION"
REL_CHILD_CONFIRMS_PARENT = "CHILD_CONFIRMS_PARENT"
REL_CHILD_CONTINUES_PARENT = "CHILD_CONTINUES_PARENT"
REL_LOCAL_EXHAUSTION_WITHIN_PARENT_CONTINUATION = "LOCAL_EXHAUSTION_WITHIN_PARENT_CONTINUATION"
REL_LOCAL_REVERSAL_AGAINST_PARENT = "LOCAL_REVERSAL_AGAINST_PARENT"
REL_LOCAL_BALANCE_WITHIN_PARENT_DIRECTIONAL = "LOCAL_BALANCE_WITHIN_PARENT_DIRECTIONAL"
REL_LOCAL_DIRECTIONAL_WITHIN_PARENT_BALANCE = "LOCAL_DIRECTIONAL_WITHIN_PARENT_BALANCE"
REL_CHILD_RESOLUTION_ALIGNED_WITH_PARENT = "CHILD_RESOLUTION_ALIGNED_WITH_PARENT"
REL_CHILD_RESOLUTION_AGAINST_PARENT = "CHILD_RESOLUTION_AGAINST_PARENT"
REL_PARENT_PRESSURE_DETERIORATING = "PARENT_PRESSURE_DETERIORATING"
REL_TRANSITION_PROPAGATING_UP = "TRANSITION_PROPAGATING_UP"
REL_COUNTERTREND_REACTION_ONLY = "COUNTERTREND_REACTION_ONLY"
REL_SYNCHRONIZED_EXHAUSTION = "SYNCHRONIZED_EXHAUSTION"
REL_SYNCHRONIZED_BALANCE = "SYNCHRONIZED_BALANCE"
REL_SYNCHRONIZED_RESOLUTION = "SYNCHRONIZED_RESOLUTION"
REL_PARENT_DIRECTION_SURVIVED_CHILD_REVERSAL = "PARENT_DIRECTION_SURVIVED_CHILD_REVERSAL"
REL_UNRESOLVED_CONFLICT = "UNRESOLVED_CONFLICT"

PAIR_RELATIONS: FrozenSet[str] = frozenset(
    {
        REL_UNRESOLVED,
        REL_CHILD_CONFIRMS_PARENT,
        REL_CHILD_CONTINUES_PARENT,
        REL_LOCAL_EXHAUSTION_WITHIN_PARENT_CONTINUATION,
        REL_LOCAL_REVERSAL_AGAINST_PARENT,
        REL_LOCAL_BALANCE_WITHIN_PARENT_DIRECTIONAL,
        REL_LOCAL_DIRECTIONAL_WITHIN_PARENT_BALANCE,
        REL_CHILD_RESOLUTION_ALIGNED_WITH_PARENT,
        REL_CHILD_RESOLUTION_AGAINST_PARENT,
        REL_PARENT_PRESSURE_DETERIORATING,
        REL_TRANSITION_PROPAGATING_UP,
        REL_COUNTERTREND_REACTION_ONLY,
        REL_SYNCHRONIZED_EXHAUSTION,
        REL_SYNCHRONIZED_BALANCE,
        REL_SYNCHRONIZED_RESOLUTION,
        REL_PARENT_DIRECTION_SURVIVED_CHILD_REVERSAL,
        REL_UNRESOLVED_CONFLICT,
    }
)

# Top-level hierarchy states.
HIER_UNRESOLVED = "UNRESOLVED_HIERARCHY"
HIER_STRUCTURAL_UP_ALIGNED = "STRUCTURAL_UP_ALIGNED"
HIER_STRUCTURAL_DOWN_ALIGNED = "STRUCTURAL_DOWN_ALIGNED"
HIER_LOCAL_UP_WITHIN_PARENT_DOWN = "LOCAL_UP_WITHIN_PARENT_DOWN"
HIER_LOCAL_DOWN_WITHIN_PARENT_UP = "LOCAL_DOWN_WITHIN_PARENT_UP"
HIER_LOCAL_ROTATION_WITHIN_PARENT_BALANCE = "LOCAL_ROTATION_WITHIN_PARENT_BALANCE"
HIER_LOCAL_BALANCE_WITHIN_STRUCTURAL_UP = "LOCAL_BALANCE_WITHIN_STRUCTURAL_UP"
HIER_LOCAL_BALANCE_WITHIN_STRUCTURAL_DOWN = "LOCAL_BALANCE_WITHIN_STRUCTURAL_DOWN"
HIER_TRANSITION_PROPAGATING_TO_HIGHER_TF = "TRANSITION_PROPAGATING_TO_HIGHER_TF"
HIER_MULTI_TF_BALANCE = "MULTI_TF_BALANCE"
HIER_MULTI_TF_EXHAUSTION = "MULTI_TF_EXHAUSTION"
HIER_MULTI_TF_RESOLUTION_UP = "MULTI_TF_RESOLUTION_UP"
HIER_MULTI_TF_RESOLUTION_DOWN = "MULTI_TF_RESOLUTION_DOWN"
HIER_CONFLICTED = "CONFLICTED_HIERARCHY"

HIERARCHY_STATES: FrozenSet[str] = frozenset(
    {
        HIER_UNRESOLVED,
        HIER_STRUCTURAL_UP_ALIGNED,
        HIER_STRUCTURAL_DOWN_ALIGNED,
        HIER_LOCAL_UP_WITHIN_PARENT_DOWN,
        HIER_LOCAL_DOWN_WITHIN_PARENT_UP,
        HIER_LOCAL_ROTATION_WITHIN_PARENT_BALANCE,
        HIER_LOCAL_BALANCE_WITHIN_STRUCTURAL_UP,
        HIER_LOCAL_BALANCE_WITHIN_STRUCTURAL_DOWN,
        HIER_TRANSITION_PROPAGATING_TO_HIGHER_TF,
        HIER_MULTI_TF_BALANCE,
        HIER_MULTI_TF_EXHAUSTION,
        HIER_MULTI_TF_RESOLUTION_UP,
        HIER_MULTI_TF_RESOLUTION_DOWN,
        HIER_CONFLICTED,
    }
)

# local_vs_structural_state
LVS_LOCAL_ONLY = "LOCAL_ONLY"
LVS_LOCAL_WITH_PARENT_SUPPORT = "LOCAL_WITH_PARENT_SUPPORT"
LVS_LOCAL_AGAINST_PARENT = "LOCAL_AGAINST_PARENT"
LVS_PROPAGATING = "PROPAGATING"
LVS_STRUCTURAL_MULTI_TF = "STRUCTURAL_MULTI_TF"
LVS_UNRESOLVED = "UNRESOLVED"

LOCAL_VS_STRUCTURAL: FrozenSet[str] = frozenset(
    {
        LVS_LOCAL_ONLY,
        LVS_LOCAL_WITH_PARENT_SUPPORT,
        LVS_LOCAL_AGAINST_PARENT,
        LVS_PROPAGATING,
        LVS_STRUCTURAL_MULTI_TF,
        LVS_UNRESOLVED,
    }
)

# conflict_state
CONFLICT_NONE = "NONE"
CONFLICT_PAIR = "PAIR_CONFLICT"
CONFLICT_MULTI = "MULTI_TF_CONFLICT"
CONFLICT_STALE = "STALE_PARENT_CONFLICT"


def mirror_hierarchy_state(state: str) -> str:
    """UP/DOWN symmetric counterpart of a hierarchy state."""
    mapping = {
        HIER_STRUCTURAL_UP_ALIGNED: HIER_STRUCTURAL_DOWN_ALIGNED,
        HIER_LOCAL_UP_WITHIN_PARENT_DOWN: HIER_LOCAL_DOWN_WITHIN_PARENT_UP,
        HIER_LOCAL_BALANCE_WITHIN_STRUCTURAL_UP: HIER_LOCAL_BALANCE_WITHIN_STRUCTURAL_DOWN,
        HIER_MULTI_TF_RESOLUTION_UP: HIER_MULTI_TF_RESOLUTION_DOWN,
    }
    reverse = {v: k for k, v in mapping.items()}
    if state in mapping:
        return mapping[state]
    if state in reverse:
        return reverse[state]
    return state


def default_aes3_params() -> dict:
    return {
        # Max age = cadence * multiplier before parent_state_stale.
        "stale_cadence_sec": {"M15": 900, "M30": 1800, "H1": 3600, "H4": 14400},
        "stale_multiplier": 2.0,
        "propagation_history": 16,
    }


def merge_aes3_params(config: dict | None) -> dict:
    base = default_aes3_params()
    raw = dict((config or {}).get("aes3") or {})
    for key, value in raw.items():
        if key == "stale_cadence_sec" and isinstance(value, dict):
            merged = dict(base["stale_cadence_sec"])
            merged.update({str(k).upper(): int(v) for k, v in value.items()})
            base["stale_cadence_sec"] = merged
        else:
            base[key] = value
    return base
