"""AES2 auction family / episode phase vocabulary and transition helpers."""

from __future__ import annotations

from typing import FrozenSet

TIMEFRAMES = ("M15", "M30", "H1", "H4")

# Top-level auction families (exactly one per TF).
FAMILY_UNRESOLVED = "UNRESOLVED"
FAMILY_DIRECTIONAL_UP = "DIRECTIONAL_UP"
FAMILY_DIRECTIONAL_DOWN = "DIRECTIONAL_DOWN"
FAMILY_BALANCE = "BALANCE"
FAMILY_TRANSITION = "TRANSITION"

AUCTION_FAMILIES: FrozenSet[str] = frozenset(
    {
        FAMILY_UNRESOLVED,
        FAMILY_DIRECTIONAL_UP,
        FAMILY_DIRECTIONAL_DOWN,
        FAMILY_BALANCE,
        FAMILY_TRANSITION,
    }
)

# Episode phases (fine-grained).
PHASE_UNRESOLVED = "UNRESOLVED"

PHASE_UP_PRESSURE_ACTIVE = "UP_PRESSURE_ACTIVE"
PHASE_UP_PRESSURE_EXPANDING = "UP_PRESSURE_EXPANDING"
PHASE_EXTREME_UP_PARTICIPATION = "EXTREME_UP_PARTICIPATION"
PHASE_UP_CONTINUATION_ACCEPTED = "UP_CONTINUATION_ACCEPTED"
PHASE_UP_CONTINUATION_DETERIORATING = "UP_CONTINUATION_DETERIORATING"
PHASE_UP_STOPPING_CANDIDATE = "UP_STOPPING_CANDIDATE"
PHASE_POST_UP_STRESS_REACTION = "POST_UP_STRESS_REACTION"

PHASE_DOWN_PRESSURE_ACTIVE = "DOWN_PRESSURE_ACTIVE"
PHASE_DOWN_PRESSURE_EXPANDING = "DOWN_PRESSURE_EXPANDING"
PHASE_EXTREME_DOWN_PARTICIPATION = "EXTREME_DOWN_PARTICIPATION"
PHASE_DOWN_CONTINUATION_ACCEPTED = "DOWN_CONTINUATION_ACCEPTED"
PHASE_DOWN_CONTINUATION_DETERIORATING = "DOWN_CONTINUATION_DETERIORATING"
PHASE_DOWN_STOPPING_CANDIDATE = "DOWN_STOPPING_CANDIDATE"
PHASE_POST_DOWN_STRESS_REACTION = "POST_DOWN_STRESS_REACTION"

PHASE_TRANSITION = "TRANSITION"

PHASE_BALANCE_FORMING = "BALANCE_FORMING"
PHASE_BALANCE_ESTABLISHED = "BALANCE_ESTABLISHED"
PHASE_BALANCE_ROTATION = "BALANCE_ROTATION"
PHASE_BALANCE_COMPRESSION = "BALANCE_COMPRESSION"
PHASE_BALANCE_UPPER_PRESSURE = "BALANCE_UPPER_PRESSURE"
PHASE_BALANCE_LOWER_PRESSURE = "BALANCE_LOWER_PRESSURE"
PHASE_UPSIDE_EXPANSION_ATTEMPT = "UPSIDE_EXPANSION_ATTEMPT"
PHASE_DOWNSIDE_EXPANSION_ATTEMPT = "DOWNSIDE_EXPANSION_ATTEMPT"
PHASE_FAILED_UPSIDE_BREAK = "FAILED_UPSIDE_BREAK"
PHASE_FAILED_DOWNSIDE_BREAK = "FAILED_DOWNSIDE_BREAK"
PHASE_ACCEPTANCE_ABOVE = "ACCEPTANCE_ABOVE"
PHASE_ACCEPTANCE_BELOW = "ACCEPTANCE_BELOW"
PHASE_RESOLUTION_UP = "RESOLUTION_UP"
PHASE_RESOLUTION_DOWN = "RESOLUTION_DOWN"

# Neutral internal-transfer research label (not accumulation/distribution).
PHASE_INTERNAL_TRANSFER_SUPPORT = "INTERNAL_TRANSFER_SUPPORT"

EPISODE_PHASES: FrozenSet[str] = frozenset(
    {
        PHASE_UNRESOLVED,
        PHASE_UP_PRESSURE_ACTIVE,
        PHASE_UP_PRESSURE_EXPANDING,
        PHASE_EXTREME_UP_PARTICIPATION,
        PHASE_UP_CONTINUATION_ACCEPTED,
        PHASE_UP_CONTINUATION_DETERIORATING,
        PHASE_UP_STOPPING_CANDIDATE,
        PHASE_POST_UP_STRESS_REACTION,
        PHASE_DOWN_PRESSURE_ACTIVE,
        PHASE_DOWN_PRESSURE_EXPANDING,
        PHASE_EXTREME_DOWN_PARTICIPATION,
        PHASE_DOWN_CONTINUATION_ACCEPTED,
        PHASE_DOWN_CONTINUATION_DETERIORATING,
        PHASE_DOWN_STOPPING_CANDIDATE,
        PHASE_POST_DOWN_STRESS_REACTION,
        PHASE_TRANSITION,
        PHASE_BALANCE_FORMING,
        PHASE_BALANCE_ESTABLISHED,
        PHASE_BALANCE_ROTATION,
        PHASE_BALANCE_COMPRESSION,
        PHASE_BALANCE_UPPER_PRESSURE,
        PHASE_BALANCE_LOWER_PRESSURE,
        PHASE_UPSIDE_EXPANSION_ATTEMPT,
        PHASE_DOWNSIDE_EXPANSION_ATTEMPT,
        PHASE_FAILED_UPSIDE_BREAK,
        PHASE_FAILED_DOWNSIDE_BREAK,
        PHASE_ACCEPTANCE_ABOVE,
        PHASE_ACCEPTANCE_BELOW,
        PHASE_RESOLUTION_UP,
        PHASE_RESOLUTION_DOWN,
        PHASE_INTERNAL_TRANSFER_SUPPORT,
    }
)

UP_PHASES = frozenset(
    {
        PHASE_UP_PRESSURE_ACTIVE,
        PHASE_UP_PRESSURE_EXPANDING,
        PHASE_EXTREME_UP_PARTICIPATION,
        PHASE_UP_CONTINUATION_ACCEPTED,
        PHASE_UP_CONTINUATION_DETERIORATING,
        PHASE_UP_STOPPING_CANDIDATE,
        PHASE_POST_UP_STRESS_REACTION,
        PHASE_RESOLUTION_UP,
    }
)

DOWN_PHASES = frozenset(
    {
        PHASE_DOWN_PRESSURE_ACTIVE,
        PHASE_DOWN_PRESSURE_EXPANDING,
        PHASE_EXTREME_DOWN_PARTICIPATION,
        PHASE_DOWN_CONTINUATION_ACCEPTED,
        PHASE_DOWN_CONTINUATION_DETERIORATING,
        PHASE_DOWN_STOPPING_CANDIDATE,
        PHASE_POST_DOWN_STRESS_REACTION,
        PHASE_RESOLUTION_DOWN,
    }
)

BALANCE_PHASES = frozenset(
    {
        PHASE_BALANCE_FORMING,
        PHASE_BALANCE_ESTABLISHED,
        PHASE_BALANCE_ROTATION,
        PHASE_BALANCE_COMPRESSION,
        PHASE_BALANCE_UPPER_PRESSURE,
        PHASE_BALANCE_LOWER_PRESSURE,
        PHASE_UPSIDE_EXPANSION_ATTEMPT,
        PHASE_DOWNSIDE_EXPANSION_ATTEMPT,
        PHASE_FAILED_UPSIDE_BREAK,
        PHASE_FAILED_DOWNSIDE_BREAK,
        PHASE_ACCEPTANCE_ABOVE,
        PHASE_ACCEPTANCE_BELOW,
        PHASE_INTERNAL_TRANSFER_SUPPORT,
    }
)


def family_for_phase(phase: str) -> str:
    if phase in UP_PHASES:
        return FAMILY_DIRECTIONAL_UP
    if phase in DOWN_PHASES:
        return FAMILY_DIRECTIONAL_DOWN
    if phase in BALANCE_PHASES:
        return FAMILY_BALANCE
    if phase == PHASE_TRANSITION:
        return FAMILY_TRANSITION
    return FAMILY_UNRESOLVED


def mirror_phase(phase: str) -> str:
    """Return the UP/DOWN symmetric counterpart of a phase."""
    mapping = {
        PHASE_UP_PRESSURE_ACTIVE: PHASE_DOWN_PRESSURE_ACTIVE,
        PHASE_UP_PRESSURE_EXPANDING: PHASE_DOWN_PRESSURE_EXPANDING,
        PHASE_EXTREME_UP_PARTICIPATION: PHASE_EXTREME_DOWN_PARTICIPATION,
        PHASE_UP_CONTINUATION_ACCEPTED: PHASE_DOWN_CONTINUATION_ACCEPTED,
        PHASE_UP_CONTINUATION_DETERIORATING: PHASE_DOWN_CONTINUATION_DETERIORATING,
        PHASE_UP_STOPPING_CANDIDATE: PHASE_DOWN_STOPPING_CANDIDATE,
        PHASE_POST_UP_STRESS_REACTION: PHASE_POST_DOWN_STRESS_REACTION,
        PHASE_BALANCE_UPPER_PRESSURE: PHASE_BALANCE_LOWER_PRESSURE,
        PHASE_UPSIDE_EXPANSION_ATTEMPT: PHASE_DOWNSIDE_EXPANSION_ATTEMPT,
        PHASE_FAILED_UPSIDE_BREAK: PHASE_FAILED_DOWNSIDE_BREAK,
        PHASE_ACCEPTANCE_ABOVE: PHASE_ACCEPTANCE_BELOW,
        PHASE_RESOLUTION_UP: PHASE_RESOLUTION_DOWN,
    }
    reverse = {v: k for k, v in mapping.items()}
    if phase in mapping:
        return mapping[phase]
    if phase in reverse:
        return reverse[phase]
    return phase
