"""Observe-only structural stop/take and trade-economics shadow (SHADOW-STP1)."""

from __future__ import annotations

WRITE_BOUNDARY_VIOLATION = "SHADOW_STP_WRITE_BOUNDARY_VIOLATION"
BASELINE_DIVERGENCE = "SHADOW_STP_BASELINE_DIVERGENCE"
LOOKAHEAD_VIOLATION = "SHADOW_STP_LOOKAHEAD_VIOLATION"
BLOCKED_NO_EXACT = "SHADOW_STP1_BLOCKED_NO_EXACT_INTRABAR_VOLUME"
BLOCKED_NO_CLASS = "SHADOW_STP1_BLOCKED_NO_CAUSAL_VOLUME_CLASSIFICATION"
READY_BLOCKED_HISTORY = "SHADOW_STP1_READY_BLOCKED_INSUFFICIENT_CAUSAL_HISTORY"
STATUS_ACTIVE = "SHADOW_STP1_STRUCTURAL_PROTECTION_OBSERVE_ONLY_ACTIVE"

EXPECTED_EPOCH = "PER_TF_EQUITY_1PCT_V1_20260729_181431"
EXPECTED_ACTIVE_FP = "ca13177674222de7991dc26688ee2f91e018e5728a1660af6dc81c326acf7129"
EXPECTED_PARENT_FP = "a6a916a767c6cfe83e9eb4581103d422bfc1adad6a56dfbf8f867930c129cb5a"

TIMEFRAMES = ("M15", "M30", "H1", "H4")
TF_SECONDS = {"M15": 900, "M30": 1800, "H1": 3600, "H4": 14400}

# Canonical volume_class values observed in volume_classification_memory.parquet
CANONICAL_VOLUME_CLASSES = {
    "climax": "CLIMAX",
    "stopping": "STOPPING",
    "high_average": "HIGH_AVERAGE_VOLUME",
    "low_small": "LOW_SMALL",
}
SIGNIFICANT_CLASSES = frozenset({"CLIMAX", "STOPPING", "HIGH_AVERAGE_VOLUME"})

ZONE_METHODS = ("POC_BIN", "POC_CONTIGUOUS_50", "POC_VALUE_AREA_70")
VOLUME_CLASS_POLICIES = ("CLIMAX_ONLY", "CLIMAX_OR_STOPPING", "ALL_CANONICAL_SIGNIFICANT")
BUFFER_POLICIES = ("DISTAL_PLUS_ONE_TICK", "DISTAL_PLUS_EXECUTABLE_SPREAD")
TAKE_POLICIES = ("TP_PROXIMAL", "TP_POC", "TP_DISTAL")
ECONOMIC_GATES = (
    "NO_ECONOMIC_GATE",
    "NET_R_MIN_075",
    "NET_R_MIN_100",
    "NET_R_MIN_125",
    "NET_R_MIN_150",
    "NET_R_MIN_200",
)

# BTCUSDT observed price quantum in raw aggTrade (not invented ATR/pct).
DEFAULT_TICK_SIZE = 0.01
SHADOW_MODEL_VERSION = "SHADOW_STP1_V1"
