"""Observe-only structural stop/take and trade-economics shadow (SHADOW-STP2)."""

from __future__ import annotations

WRITE_BOUNDARY_VIOLATION = "SHADOW_STP_WRITE_BOUNDARY_VIOLATION"
BASELINE_DIVERGENCE = "SHADOW_STP_BASELINE_DIVERGENCE"
LOOKAHEAD_VIOLATION = "SHADOW_STP_LOOKAHEAD_VIOLATION"
BLOCKED_NO_EXACT = "SHADOW_STP1_BLOCKED_NO_EXACT_INTRABAR_VOLUME"
BLOCKED_NO_CLASS = "SHADOW_STP1_BLOCKED_NO_CAUSAL_VOLUME_CLASSIFICATION"
READY_BLOCKED_HISTORY = "SHADOW_STP1_READY_BLOCKED_INSUFFICIENT_CAUSAL_HISTORY"
STATUS_ACTIVE = "SHADOW_STP2_PER_TIMEFRAME_STRUCTURAL_RESEARCH_ACTIVE"
STATUS_STP21_COVERAGE = "SHADOW_STP2_1_COVERAGE_INTEGRITY_PROVEN"
STATUS_INSUFFICIENT_REACTION = "SHADOW_STP2_ACTIVE_WITH_INSUFFICIENT_REACTION_HISTORY"
STATUS_POLICY_INTEGRITY = "SHADOW_STP1_1_POLICY_INTEGRITY_PROVEN"
STATUS_EVIDENCE_GATE_FAILURE = "SHADOW_STP1_1_POLICY_EVIDENCE_GATE_FAILURE"
STATUS_CANONICAL_ISOLATION_FAILURE = "SHADOW_STP2_CANONICAL_ISOLATION_FAILURE"
STATUS_BASELINE_DIVERGENCE_STP11 = "SHADOW_STP2_BASELINE_DIVERGENCE"
STATUS_LOOKAHEAD_STP11 = "SHADOW_STP2_REACTION_LOOKAHEAD_VIOLATION"
STATUS_CLASS_PARITY_BLOCKED = "SHADOW_STP2_BLOCKED_CLASSIFICATION_PARITY_FAILURE"
STATUS_MARKET_RECON_FAILURE = "SHADOW_STP2_BLOCKED_MARKET_RECONSTRUCTION_FAILURE"
STATUS_WRITE_BOUNDARY = "SHADOW_STP2_WRITE_BOUNDARY_VIOLATION"
STATUS_COVERAGE_INTEGRITY_FAILURE = "SHADOW_STP2_1_BLOCKED_COVERAGE_INTEGRITY_FAILURE"

EXPECTED_EPOCH = "PER_TF_EQUITY_1PCT_V1_20260729_181431"
EXPECTED_ACTIVE_FP = "ca13177674222de7991dc26688ee2f91e018e5728a1660af6dc81c326acf7129"
EXPECTED_PARENT_FP = "a6a916a767c6cfe83e9eb4581103d422bfc1adad6a56dfbf8f867930c129cb5a"
HISTORICAL_STP11_MANIFEST = "e300d491fe470df4df754369ebbaedac25e66505950b555e76d0579467f7115b"

TIMEFRAMES = ("M15", "M30", "H1", "H4")
TF_SECONDS = {"M15": 900, "M30": 1800, "H1": 3600, "H4": 14400}

CANONICAL_VOLUME_CLASSES = {
    "climax": "CLIMAX",
    "stopping": "STOPPING",
    "high_average": "HIGH_AVERAGE_VOLUME",
    "low_small": "LOW_SMALL",
}
SIGNIFICANT_CLASSES = frozenset({"CLIMAX", "STOPPING", "HIGH_AVERAGE_VOLUME"})

ZONE_METHODS = ("POC_BIN", "POC_CONTIGUOUS_50", "POC_VALUE_AREA_70")
VOLUME_CLASS_POLICIES = ("CLIMAX_ONLY", "CLIMAX_OR_STOPPING", "ALL_CANONICAL_SIGNIFICANT")
BUFFER_POLICIES = ("ONE_TICK", "EXECUTABLE_SPREAD", "MAX_ONE_TICK_OR_SPREAD")
TAKE_POLICIES = ("TARGET_PROXIMAL", "TARGET_POC", "TARGET_DISTAL")
ECONOMIC_GATES = (
    "NO_NET_R_GATE",
    "NET_R_MIN_075",
    "NET_R_MIN_100",
    "NET_R_MIN_125",
    "NET_R_MIN_150",
    "NET_R_MIN_200",
)

DEFAULT_TICK_SIZE = 0.01
SHADOW_MODEL_VERSION = "SHADOW_STP2_1_V1"
LEGACY_MANIFEST_INVALIDATION_REASON = "STP2_GENERATION_SUPERSEDED_NOT_MIXED"
COVERAGE_INTEGRITY_CONTRACT = "STP2_1_COVERAGE_METRICS_V1"
# Classification/zone-age policy thresholds unchanged. These lookbacks only control
# how much pre-decision exact agg_trade history is loaded for reconstruction.
# Wall-clock hours so H4/H1 receive usable causal history, not just N short bars.
CAUSAL_LOOKBACK_HOURS_BY_TF = {"M15": 24, "M30": 24, "H1": 48, "H4": 96}
# Kept for tests/compat: approximate bar counts at the hour lookbacks above.
LOOKBACK_BARS_BY_TF = {"M15": 96, "M30": 48, "H1": 48, "H4": 24}
