"""Column projections for dashboard parquet reads — avoid wide full-file decode."""

from __future__ import annotations

# Default columns per parquet for monitoring / research snapshots.
DASHBOARD_PARQUET_COLUMNS: dict[str, list[str]] = {
    "runtime_engine_state.parquet": ["engine", "status", "duration", "timestamp"],
    "auction_synthesis_memory.parquet": ["timestamp", "synthesis_state"],
    "live_market_feed.parquet": ["timestamp", "open", "high", "low", "close", "volume"],
    "context_decision_log.parquet": [
        "decision_id",
        "decision_written_at_utc",
        "candle_timestamp",
        "active_market_context",
        "lifecycle_state",
        "candidate_context",
        "paper_action_candidate",
        "intended_side",
        "paper_loop_allowed",
        "paper_signal_write_allowed",
        "confidence",
        "expected_edge_bps",
        "edge_signal_rule",
        "context_start_event",
        "context_start_event_source",
        "freshness_status",
    ],
    "market_context_lifecycle_memory.parquet": [
        "timestamp",
        "raw_market_context",
        "active_market_context",
        "lifecycle_state",
        "candidate_context",
        "action_allowed",
        "action_reason",
        "shadow_only",
    ],
    "candle_structure_memory.parquet": ["timestamp", "open", "high", "low", "close", "volume", "timeframe"],
    "runtime_cognition_memory.parquet": ["timestamp", "cognition_state", "raw_conviction"],
    "probabilistic_auction_memory.parquet": [
        "timestamp",
        "trend_confidence",
        "market_state",
        "auction_regime",
        "regime_state",
        "conviction_probability",
        "raw_conviction",
        "disciplined_conviction",
        "calibrated_conviction",
        "conflict_density",
        "survival_half_life",
        "saturation_score",
        "calibration_drift_score",
        "resilience_score",
        "calibration_stability_score",
        "semantic_fragility_score",
        "contradiction_escalation_score",
        "unresolved_contradiction_score",
        "entropy_interaction",
        "reinforcement_component",
        "ontology_overlap_matrix",
        "ontology_ambiguity_heatmap",
        "ontology_drift_score",
        "ontology_stability_score",
        "grey_zone_expansion_rate",
    ],
    "market_state_memory.parquet": [
        "timestamp",
        "market_state",
        "market_bias",
        "market_state_confidence",
        "rule_id",
    ],
    "trading_state_memory.parquet": [
        "timestamp",
        "trading_state",
        "confidence_band",
        "entry_eligible",
        "execution_posture",
        "market_state",
        "market_state_confidence",
    ],
    "trading_state_feature_snapshots.parquet": [
        "timestamp",
        "trading_state",
        "entry_eligible",
        "execution_posture",
        "snapshot_id",
        "market_state",
        "market_state_confidence",
    ],
    "model_monitoring_memory.parquet": [
        "timestamp",
        "rollback_warning",
        "promotion_eligible",
        "rollback_reasons",
        "promotion_reasons",
        "psi_label",
        "psi_feature_max",
        "macro_f1",
        "loss_recall",
    ],
    "economic_validation_memory.parquet": [
        "validation_horizon",
        "validation_status",
        "economic_outcome",
        "completed_at",
        "timestamp",
    ],
    "trading_state_validation_memory.parquet": [
        "timestamp",
        "validation_horizon",
        "validation_status",
        "outcome",
    ],
    "shadow_inference_memory.parquet": [
        "prediction_timestamp",
        "decision_timestamp",
        "snapshot_id",
        "predicted_class",
        "class_probabilities",
        "evaluation_status",
        "actual_outcome",
        "macro_f1",
        "balanced_accuracy",
        "loss_recall",
    ],
    "toxic_box_memory.parquet": [
        "timestamp",
        "created_at",
        "lineage_propagation_timestamp",
        "toxic_type",
        "severity",
        "snapshot_id",
    ],
    "state_transition_memory.parquet": ["timestamp", "transition_state"],
    "auction_reinforcement_memory.parquet": ["timestamp"],
    "intermediate_cognition_memory.parquet": ["timestamp"],
    "runtime_dependency_state.parquet": ["timestamp", "engine", "status"],
    "climactic_behavior_memory.parquet": ["timestamp"],
    "multi_timeframe_synthesis.parquet": ["timestamp"],
    "htf_structure_memory.parquet": ["timestamp"],
    "htf_ltf_context_memory.parquet": ["timestamp"],
}


def resolve_columns(name: str, columns: list[str] | None) -> list[str] | None:
    if columns is not None:
        return columns
    return DASHBOARD_PARQUET_COLUMNS.get(name)
