import type { OpsSnapshot } from "../types/ops";

/**
 * Honest offline snapshot when :8080 is unavailable.
 * Must not invent Operational health or live zeros.
 */
export function buildOpsFallbackSnapshot(): OpsSnapshot {
  const now = new Date().toISOString();

  return {
    generated_at: now,
    snapshot_mode: "FALLBACK_OFFLINE",
    overall_health: "LIVE_DATA_UNAVAILABLE",
    overall_reason: "OPS API disconnected — showing last-known / static layout",
    ribbon: [
      { key: "system_health", label: "System Health", level: "GREY", value: "LIVE_DATA_UNAVAILABLE" },
      { key: "pipeline", label: "Pipeline", level: "GREY", value: "UNAVAILABLE" },
      { key: "live_feed", label: "Live Feed", level: "GREY", value: "API OFFLINE" },
    ],
    engines: [],
    parquet: {
      summary_level: "GREY",
      live_count: 0,
      stale_count: 0,
      delayed_count: 0,
      missing_count: 0,
      optional_stale_count: 0,
      archived_count: 0,
      stale_files: [],
      delayed_files: [],
      missing_files: [],
      required: [],
      optional: [],
      archived: [],
      all: [],
    },
    collectors: {
      level: "GREY",
      collectors: [],
      required: [],
      optional: [],
      legacy: [],
    },
    pipeline: {
      current_cycle: null,
      average_cycle_duration_s: null,
      last_cycle_duration_s: null,
      uptime_seconds: null,
      failed_engine_count: null,
      stalled_engine_count: null,
      heartbeat_level: "GREY",
      active_state: "UNAVAILABLE",
    },
    feed_confidence: {
      overall: "GREY",
      ws: { level: "GREY", label: "WS", reason: "OPS API disconnected" },
      write: { level: "GREY", label: "WRITE", reason: "OPS API disconnected" },
      consume: { level: "GREY", label: "CONSUME", reason: "OPS API disconnected" },
    },
    stability: {
      runtime_uptime_s: null,
      collector_uptime_s: null,
      websocket_uptime_s: null,
      restart_count: null,
      disconnect_count: null,
      recent_events: [],
    },
    health: {
      level: "UNKNOWN",
      display_status: "LIVE_DATA_UNAVAILABLE",
      primary_reason: "LIVE DATA UNAVAILABLE · OPS API disconnected",
      reasons: ["Showing last-known snapshot", `Last known at: ${now}`],
      critical_reasons: [],
      degraded_reasons: [],
      cpu_percent: null,
      memory_percent: null,
      disk_percent: null,
    },
    alerts: [],
    alert_groups: {
      actionable: [],
      informational: [],
      all: [],
    },
    processes: [],
    multi_timeframe: [],
    paper: {
      display_status: "MIGRATED",
      representation: "MIGRATED_TO_TIMEFRAME_TRADERS",
      requirement: "NOT_REQUIRED",
      is_controller_failure: false,
      process_health: "STOPPED",
      detail: "Replaced by independent M15, M30, H1 and H4 traders",
    },
    known_limitations: [],
    legacy_components: [],
    timeframe_traders: {
      activated: false,
      traders: [],
    },
    research_pipeline: {
      generated_at: now,
      pipeline: {
        step_count: 0,
        expected_step_count: 0,
        in_sync: false,
        engines: [],
        last_cycle_duration_s: null,
        average_cycle_duration_s: null,
      },
      decision_layer: {
        level: "GREY",
        status_label: "UNAVAILABLE",
        market_state: "UNAVAILABLE",
        market_bias: "UNAVAILABLE",
        trading_state: "UNAVAILABLE",
        confidence_band: "UNAVAILABLE",
        entry_eligible: false,
        execution_posture: "STAND_ASIDE",
      },
      model_governance: {
        level: "GREY",
        governance_status: "GOVERNANCE_MISSING",
        active_model: "—",
        shadow_model: "—",
        promotion_eligible: false,
        promotion_eligible_label: "N/A",
      },
      economic_validation: {
        level: "GREY",
        rows: 0,
        complete_h4h: 0,
        pending_h4h: 0,
      },
      shadow_inference: {
        level: "GREY",
        validation_status: "UNAVAILABLE",
        rows: 0,
        evaluated_rows: 0,
        pending_rows: 0,
      },
      toxic_box: {
        level: "GREY",
        severity_label: "HISTORICAL_ONLY",
        display_status: "HISTORICAL_ONLY",
        rows: 0,
        events: 0,
        monitoring_mode: "unavailable",
        current: {
          status: "NOT_CONNECTED",
          metrics_available: false,
        },
        historical: {
          status: "HISTORICAL_ONLY",
          metrics_available: true,
        },
      },
      drift_monitoring: {
        level: "GREY",
        severity_label: "UNAVAILABLE",
        psi: null,
        macro_f1: null,
        loss_recall: null,
        monitoring_rows: 0,
      },
      model_summary: {
        level: "GREY",
        status: "UNAVAILABLE",
        model: "—",
        governance_status: "UNAVAILABLE",
      },
      model_assurance: {
        status: "MISSING_SOURCE",
        overall_assurance_status: "MISSING_SOURCE",
        runtime_safety_status: "UNKNOWN",
        runtime_impact: "NON_BLOCKING",
        promotion_control: "GOVERNANCE_GATE",
        scope: "CURRENT_ACTIVE_MODEL_ONLY",
        environment_blockers: [],
        promotion_blockers: [],
        current_blockers: [],
        current_incidents: [],
        current_toxic_events: [],
        missing_sources: ["latest_summary"],
        stale_sources: [],
      },
      ribbon_extensions: [],
    },
    runtime_failure_audit: {
      exists: false,
      path: "runtime_failure_audit.jsonl",
      total_count: 0,
      recent_count: 0,
      malformed_count: 0,
      latest: null,
      recent: [],
    },
    runtime_skipped_engine_audit: {
      exists: false,
      path: "runtime_skipped_engine_audit.jsonl",
      total_count: 0,
      recent_count: 0,
      malformed_count: 0,
      latest: null,
      recent: [],
    },
  };
}
