import type { OpsSnapshot } from "../types/ops";

const ENGINE_NAMES = [
  "candle_structure_engine_v1.py",
  "volume_classification_engine_v1.py",
  "schema_validation_engine_v1.py",
  "behavioral_sequence_memory_v1.py",
  "behavioral_volume_observer_v1.py",
  "microstructure_candle_engine_v1.py",
  "volume_response_engine_v1.py",
  "climactic_behavior_engine_v1.py",
  "auction_convergence_engine_v1.py",
  "auction_synthesis_engine_v1.py",
  "stage2_cognition_runtime_v1.py",
  "runtime_cognition_engine_v1.py",
  "intermediate_cognition_engine_v1.py",
  "auction_reinforcement_engine_v1.py",
  "probabilistic_auction_engine_v1.py",
  "auction_context_arbitration_engine_v1.py",
  "auction_decay_engine_v1.py",
  "state_transition_engine_v1.py",
  "adaptive_meta_cognition_engine_v1.py",
] as const;

/** Static Operations snapshot so Platform UI renders without live :8080 API. */
export function buildOpsFallbackSnapshot(): OpsSnapshot {
  const now = new Date().toISOString();

  return {
    generated_at: now,
    ribbon: [
      { key: "system_health", label: "System Health", level: "GREEN", value: "HEALTHY" },
      { key: "pipeline", label: "Pipeline", level: "GREEN", value: "RUNNING" },
      { key: "validation", label: "Validation", level: "YELLOW", value: "REVIEW" },
      { key: "trading_state", label: "Trading State", level: "GREEN", value: "OBSERVE" },
      { key: "shadow_model", label: "Shadow Model", level: "GREEN", value: "ACTIVE" },
      { key: "governance", label: "Governance", level: "GREEN", value: "STABLE" },
      { key: "drift", label: "Drift Monitoring", level: "GREEN", value: "STABLE" },
      { key: "toxic_box", label: "Toxic Box", level: "GREEN", value: "QUIET" },
      { key: "live_feed", label: "Live Feed", level: "GREY", value: "OPTIONAL / OFFLINE" },
    ],
    engines: ENGINE_NAMES.map((engine) => ({
      engine,
      short_name: engine.replace(/_engine_v1\.py$|_v1\.py$/, ""),
      status: "HEALTHY",
      classification: "REQUIRED",
      affects_health: true,
      last_run: now,
      last_run_ago: "—",
      duration_s: 0.2,
      mode: "inprocess",
      note: "fallback snapshot",
    })),
    parquet: {
      summary_level: "GREEN",
      live_count: 12,
      stale_count: 0,
      delayed_count: 0,
      missing_count: 0,
      optional_stale_count: 0,
      archived_count: 0,
      stale_files: [],
      delayed_files: [],
      missing_files: [],
      required: [],
      optional: [],
      archived: [],
      all: [],
    },
    collectors: {
      level: "GREEN",
      collectors: [
        {
          name: "live_market_feed",
          status: "CONNECTED",
          level: "GREEN",
          classification: "REQUIRED",
          affects_health: true,
          age_seconds: 5,
          last_message: now,
        },
      ],
      required: [],
      optional: [],
      legacy: [],
    },
    pipeline: {
      current_cycle: 0,
      average_cycle_duration_s: 0,
      uptime_seconds: 0,
      failed_engine_count: 0,
      failed_required_engine_count: 0,
      failed_optional_engine_count: 0,
      timeout_count: 0,
      timeout_optional_count: 0,
      stalled_engine_count: 0,
      heartbeat_level: "GREEN",
      active_state: "IDLE",
    },
    feed_confidence: {
      overall: "GREY",
      ws: { level: "GREY", label: "WS", reason: "Live feed optional / offline" },
      write: { level: "GREY", label: "WRITE", reason: "Live feed optional / offline" },
      consume: { level: "GREY", label: "CONSUME", reason: "Live feed optional / offline" },
    },
    stability: {
      runtime_uptime_s: 0,
      collector_uptime_s: 0,
      websocket_uptime_s: 0,
      restart_count: 0,
      disconnect_count: 0,
      recent_events: [],
    },
    health: {
      level: "HEALTHY",
      primary_reason: "Fallback Operations snapshot (live API optional)",
      reasons: ["Showing last-known / static Operations layout without live :8080 feed"],
      critical_reasons: [],
      degraded_reasons: [],
      cpu_percent: 12,
      memory_percent: 34,
      disk_percent: 41,
      deferred_engine_count: 0,
      optional_offline_count: 1,
    },
    alerts: [
      {
        id: "live-feed-optional",
        severity: "INFO",
        type: "LIVE_FEED",
        message: "Live ops feed optional / offline — showing fallback Operations snapshot",
        timestamp: now,
        count: 1,
        actionable: false,
        ignored_by_health: true,
      },
    ],
    alert_groups: {
      actionable: [],
      informational: [
        {
          id: "live-feed-optional",
          severity: "INFO",
          type: "LIVE_FEED",
          message: "Live ops feed optional / offline — showing fallback Operations snapshot",
          timestamp: now,
          count: 1,
          actionable: false,
          ignored_by_health: true,
        },
      ],
      all: [
        {
          id: "live-feed-optional",
          severity: "INFO",
          type: "LIVE_FEED",
          message: "Live ops feed optional / offline — showing fallback Operations snapshot",
          timestamp: now,
          count: 1,
          actionable: false,
          ignored_by_health: true,
        },
      ],
    },
    research_pipeline: {
      generated_at: now,
      pipeline: {
        step_count: ENGINE_NAMES.length,
        expected_step_count: ENGINE_NAMES.length,
        in_sync: true,
        engines: [...ENGINE_NAMES],
        last_cycle_duration_s: null,
        average_cycle_duration_s: null,
      },
      decision_layer: {
        level: "GREEN",
        status_label: "OBSERVE",
        market_state: "NEUTRAL",
        market_bias: "NEUTRAL",
        trading_state: "OBSERVE",
        confidence_band: "LOW",
        entry_eligible: false,
        execution_posture: "STAND_ASIDE",
      },
      model_governance: {
        level: "GREEN",
        governance_status: "STABLE",
        active_model: "—",
        shadow_model: "—",
        promotion_eligible: false,
        promotion_eligible_label: "N/A",
      },
      economic_validation: {
        level: "YELLOW",
        rows: 0,
        complete_h4h: 0,
        pending_h4h: 0,
      },
      shadow_inference: {
        level: "GREEN",
        validation_status: "IDLE",
        rows: 0,
        evaluated_rows: 0,
        pending_rows: 0,
      },
      toxic_box: {
        level: "GREEN",
        severity_label: "QUIET",
        rows: 0,
        events: 0,
        events_last_7d: 0,
        toxic_rate_7d: 0,
        monitoring_mode: "observe",
        trend: "flat",
      },
      drift_monitoring: {
        level: "GREEN",
        severity_label: "STABLE",
        psi: null,
        macro_f1: null,
        loss_recall: null,
        monitoring_rows: 0,
      },
      model_summary: {
        level: "GREEN",
        status: "IDLE",
        model: "—",
        governance_status: "STABLE",
      },
      ribbon_extensions: [
        { key: "trading_state", label: "Trading State", level: "GREEN", value: "OBSERVE" },
        { key: "shadow_model", label: "Shadow Model", level: "GREEN", value: "IDLE" },
        { key: "governance", label: "Governance", level: "GREEN", value: "STABLE" },
        { key: "drift", label: "Drift Monitoring", level: "GREEN", value: "STABLE" },
        { key: "toxic_box", label: "Toxic Box", level: "GREEN", value: "QUIET" },
      ],
    },
    runtime_failure_audit: {
      exists: false,
      path: "runtime_failure_audit.jsonl",
      total_count: 0,
      recent_count: 0,
      malformed_count: 0,
      latest: null,
      recent: [],
    },
    runtime_skipped_engine_audit: {
      exists: false,
      path: "runtime_skipped_engine_audit.jsonl",
      total_count: 0,
      recent_count: 0,
      malformed_count: 0,
      latest: null,
      recent: [],
    },
  };
}
