"""S4.1 production activation support: gates, backups, legacy migration.

Read-only helpers plus explicit, reversible write steps. Nothing here places
exchange calls or enables real execution.
"""

from __future__ import annotations

import hashlib
import json
import os
import shutil
import subprocess
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import pandas as pd

from .command_bus import CommandBusPaths
from .trader_book import atomic_write_json

ROOT = Path(__file__).resolve().parents[3]
RESEARCH = ROOT / "data" / "research"
LEGACY_PAPER_DIR = RESEARCH / "paper_simulator"
LEGACY_PID = ROOT / "run" / "bounded_paper_trading_controller_auto_ledger.pid"
MANAGER_DIR = ROOT / "data" / "trading" / "manager"
ACTIVATION_PATH = MANAGER_DIR / "activation.json"
LEGACY_MIGRATION_PATH = MANAGER_DIR / "legacy_migration.json"

MODE_EMPTY = "EMPTY"
MODE_CLOSED_HISTORY_ONLY = "CLOSED_HISTORY_ONLY"
MODE_OPEN_POSITION_PRESENT = "OPEN_POSITION_PRESENT"
MODE_AMBIGUOUS = "AMBIGUOUS"

BLOCKED_BY_LEGACY_OPEN = "S4_ACTIVATION_BLOCKED_BY_LEGACY_OPEN_POSITION"
BLOCKED_BY_LEGACY_INTRABAR_EPOCH = "S4_ACTIVATION_BLOCKED_BY_LEGACY_INTRABAR_EPOCH"

INTRABAR_PAPER_ROOT = ROOT / "data" / "trading" / "intrabar_paper"
INTRABAR_EPOCHS_ROOT = ROOT / "data" / "trading" / "paper_epochs"
INTRABAR_JOURNAL_ROOT = ROOT / "data" / "cognition" / "intrabar_context_events"

# Only the datasets the legacy global paper controller itself appends to. The
# rest of data/research/paper_simulator/ is regenerated by research and visual
# tooling and must stay writable.
LEGACY_LEDGER_FILES = (
    "paper_signals.parquet",
    "paper_orders.parquet",
    "paper_trades.parquet",
    "paper_positions.parquet",
    "paper_events.parquet",
    "paper_equity_curve.parquet",
    "paper_risk_blocks.parquet",
    "bounded_paper_controller_actions.parquet",
    "bounded_paper_controller_cycles.parquet",
)

VISUAL_INVARIANT_FILES = (
    "dashboard/frontend/src/index.css",
    "apps/context_visualizer/public/styles.css",
    "apps/context_visualizer/public/lifecycle.css",
    "dashboard/frontend/src/components/ops/OpsDashboard.tsx",
    "dashboard/frontend/src/types/ops.ts",
    "dashboard/frontend/src/api/opsFallbackSnapshot.ts",
)

SEMANTIC_INVARIANT_DATASETS = (
    "data/cognition/final_market_context_memory.parquet",
    "data/cognition/market_context_lifecycle_memory.parquet",
    "data/cognition/multi_timeframe_synthesis.parquet",
    "data/cognition/multi_timeframe_availability_memory.parquet",
    "data/live/context_decision_log.parquet",
    "data/live/live_market_feed.parquet",
)


def utc_now() -> str:
    return datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")


def stamp_now() -> str:
    return datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")


def sha256_of(path: Path) -> str | None:
    if not path.exists() or not path.is_file():
        return None
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _jsonl_rows(path: Path) -> list[dict[str, Any]]:
    if not path.exists():
        return []
    rows: list[dict[str, Any]] = []
    try:
        text = path.read_text(encoding="utf-8")
    except OSError:
        return []
    for line in text.splitlines():
        if not line.strip():
            continue
        try:
            row = json.loads(line)
        except json.JSONDecodeError:
            continue
        if isinstance(row, dict):
            rows.append(row)
    return rows


def _rel_to_root(path: Path) -> str:
    try:
        return str(path.relative_to(ROOT))
    except ValueError:
        return str(path)


def intrabar_legacy_epoch_preflight() -> dict[str, Any]:
    """Inventory active LIVE1B intrabar epoch for S4.1 activation blockers."""
    detail: dict[str, Any] = {
        "active_epoch_path": _rel_to_root(INTRABAR_EPOCHS_ROOT / "active.json"),
        "open_positions": 0,
        "unconsumed_context_events": 0,
        "mode": "EMPTY",
    }
    active_path = INTRABAR_EPOCHS_ROOT / "active.json"
    if not active_path.exists():
        return detail
    try:
        active = json.loads(active_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        detail["mode"] = MODE_AMBIGUOUS
        detail["read_error"] = str(exc)
        return detail
    epoch_id = str(active.get("paper_epoch_id") or "")
    if not epoch_id:
        return detail
    detail["paper_epoch_id"] = epoch_id
    detail["rule_contract_version"] = active.get("rule_contract_version")
    books = INTRABAR_PAPER_ROOT / epoch_id / "books"
    positions = _jsonl_rows(books / "positions.jsonl")
    latest_by_id: dict[str, dict[str, Any]] = {}
    for row in positions:
        pid = str(row.get("position_id") or "")
        if pid:
            latest_by_id[pid] = row
    detail["open_positions"] = int(
        sum(1 for row in latest_by_id.values() if str(row.get("status") or "").upper() == "OPEN")
    )
    checkpoint_path = INTRABAR_PAPER_ROOT / epoch_id / "context_consumer_checkpoint.json"
    last_mono = 0
    if checkpoint_path.exists():
        try:
            ck = json.loads(checkpoint_path.read_text(encoding="utf-8"))
            last_mono = int(ck.get("last_event_monotonic_ns") or 0)
        except (OSError, json.JSONDecodeError):
            pass
    unconsumed = 0
    for path in sorted(INTRABAR_JOURNAL_ROOT.rglob("*.jsonl")) if INTRABAR_JOURNAL_ROOT.exists() else []:
        for row in _jsonl_rows(path):
            if str(row.get("epoch_id") or "") not in {"", epoch_id}:
                continue
            mono = int(row.get("event_monotonic_ns") or 0)
            if mono > last_mono:
                unconsumed += 1
    detail["unconsumed_context_events"] = unconsumed
    if detail["open_positions"] > 0 or detail["unconsumed_context_events"] > 0:
        detail["mode"] = MODE_OPEN_POSITION_PRESENT
        detail["blocking_status"] = BLOCKED_BY_LEGACY_INTRABAR_EPOCH
    else:
        detail["mode"] = MODE_EMPTY
    return detail


def legacy_ledger_mode() -> dict[str, Any]:
    positions_path = LEGACY_PAPER_DIR / "paper_positions.parquet"
    detail: dict[str, Any] = {
        "positions_path": str(positions_path.relative_to(ROOT)),
        "exists": positions_path.exists(),
        "rows": 0,
        "open_rows": 0,
        "closed_rows": 0,
        "unknown_status_rows": 0,
    }
    if not positions_path.exists():
        detail["mode"] = MODE_EMPTY
        return detail
    try:
        frame = pd.read_parquet(positions_path)
    except Exception as exc:
        detail["mode"] = MODE_AMBIGUOUS
        detail["read_error"] = str(exc)
        return detail
    detail["rows"] = int(len(frame))
    if not len(frame):
        detail["mode"] = MODE_EMPTY
        return detail
    status = frame["status"].astype(str).str.upper() if "status" in frame.columns else pd.Series(dtype=str)
    detail["open_rows"] = int((status == "OPEN").sum())
    detail["closed_rows"] = int((status == "CLOSED").sum())
    detail["unknown_status_rows"] = int(len(status) - detail["open_rows"] - detail["closed_rows"])
    if detail["open_rows"]:
        detail["mode"] = MODE_OPEN_POSITION_PRESENT
        detail["blocking_status"] = BLOCKED_BY_LEGACY_OPEN
    elif detail["unknown_status_rows"]:
        detail["mode"] = MODE_AMBIGUOUS
    else:
        detail["mode"] = MODE_CLOSED_HISTORY_ONLY
    return detail


def process_pids(needle: str) -> list[int]:
    try:
        out = subprocess.run(["ps", "-ax", "-o", "pid=,command="], capture_output=True, text=True, timeout=20).stdout
    except Exception:
        return []
    pids: list[int] = []
    for line in out.splitlines():
        line = line.strip()
        if not line or needle not in line:
            continue
        if "ps -ax" in line or "timeframe_trading_ctl" in line:
            continue
        head = line.split(" ", 1)[0]
        try:
            pids.append(int(head))
        except ValueError:
            continue
    return pids


LEGACY_CONTROLLER_SCRIPT = (
    ROOT / "scripts/live/bounded_paper_trading_controller_auto_ledger_no_real_execution.py"
)


def legacy_controller_pids() -> list[int]:
    """PIDs of the production legacy controller only.

    Identity is the repo script path, not the bare filename: sandboxed copies
    under pytest temp roots are a different process identity and must not be
    mistaken for the retired production controller.
    """
    return process_pids(str(LEGACY_CONTROLLER_SCRIPT))


def legacy_paper_archived() -> bool:
    payload = _read_json(LEGACY_MIGRATION_PATH)
    return bool(payload and payload.get("legacy_ledger_state") == "ARCHIVED_READ_ONLY")


def activation_record() -> dict[str, Any] | None:
    return _read_json(ACTIVATION_PATH)


def _read_json(path: Path) -> dict[str, Any] | None:
    if not path.exists():
        return None
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return None
    return payload if isinstance(payload, dict) else None


def candidate_summary() -> dict[str, Any] | None:
    return _read_json(RESEARCH / "s4_1_candidate_summary.json")


def evaluate_gates() -> dict[str, Any]:
    summary = candidate_summary() or {}
    gates = dict(summary.get("gates") or {})
    legacy = legacy_ledger_mode()
    intrabar = intrabar_legacy_epoch_preflight()
    checks = {
        "candidate_replay_passed": bool(gates.get("candidate_replay_passed")),
        "opposite_positions_test_passed": bool(gates.get("opposite_positions_test_passed")),
        "restart_isolation_passed": bool(gates.get("restart_isolation_passed")),
        "portfolio_risk_passed": bool(gates.get("portfolio_risk_passed")),
        "point_in_time_fill_passed": bool(gates.get("point_in_time_fill_passed")),
        "pnl_reconciliation_passed": bool(gates.get("pnl_reconciliation_passed")),
        "legacy_open_position": legacy.get("mode") == MODE_OPEN_POSITION_PRESENT,
        "legacy_mode_unambiguous": legacy.get("mode") in {MODE_EMPTY, MODE_CLOSED_HISTORY_ONLY},
        "intrabar_legacy_epoch_clean": intrabar.get("mode") == MODE_EMPTY,
        "unexplained_divergences": 0,
        "exchange_calls": 0,
    }
    blocked_reasons = [
        name
        for name in (
            "candidate_replay_passed",
            "opposite_positions_test_passed",
            "restart_isolation_passed",
            "portfolio_risk_passed",
            "point_in_time_fill_passed",
            "pnl_reconciliation_passed",
            "legacy_mode_unambiguous",
            "intrabar_legacy_epoch_clean",
        )
        if not checks[name]
    ]
    if checks["legacy_open_position"]:
        blocked_reasons.append(BLOCKED_BY_LEGACY_OPEN)
    if not checks["intrabar_legacy_epoch_clean"]:
        blocked_reasons.append(BLOCKED_BY_LEGACY_INTRABAR_EPOCH)
    return {
        "generated_at": utc_now(),
        "checks": checks,
        "legacy_ledger": legacy,
        "intrabar_legacy_epoch": intrabar,
        "candidate_status": summary.get("candidate_status"),
        "allowed": not blocked_reasons,
        "blocked_reasons": blocked_reasons,
    }


def create_backups(stamp: str | None = None) -> dict[str, Any]:
    stamp = stamp or stamp_now()
    backup_dir = RESEARCH / f"s4_1_production_backups_{stamp}"
    backup_dir.mkdir(parents=True, exist_ok=True)
    entries: list[dict[str, Any]] = []

    def copy_tree(source: Path, label: str) -> None:
        if not source.exists():
            return
        target = backup_dir / label
        if source.is_dir():
            shutil.copytree(source, target, dirs_exist_ok=True)
            for path in sorted(target.rglob("*")):
                if path.is_file():
                    entries.append(
                        {
                            "label": label,
                            "backup_path": str(path.relative_to(ROOT)),
                            "sha256": sha256_of(path),
                            "bytes": path.stat().st_size,
                        }
                    )
        else:
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(source, target)
            entries.append(
                {
                    "label": label,
                    "source_path": str(source.relative_to(ROOT)),
                    "backup_path": str(target.relative_to(ROOT)),
                    "sha256": sha256_of(target),
                    "bytes": target.stat().st_size,
                }
            )

    copy_tree(LEGACY_PAPER_DIR, "legacy_paper_simulator")
    copy_tree(ROOT / "data" / "trading", "timeframe_trading")
    copy_tree(ROOT / "config" / "timeframe_trader_risk.json", "config_timeframe_trader_risk.json")
    copy_tree(ROOT / "config" / "runtime_dataset_ownership.json", "config_runtime_dataset_ownership.json")

    manifest = {
        "generated_at": utc_now(),
        "stage": "S4_1_PRODUCTION_BACKUP",
        "stamp": stamp,
        "backup_dir": str(backup_dir.relative_to(ROOT)),
        "files": entries,
        "file_count": len(entries),
    }
    manifest_path = RESEARCH / f"s4_1_backup_manifest_{stamp}.json"
    atomic_write_json(manifest_path, manifest)
    manifest["manifest_path"] = str(manifest_path.relative_to(ROOT))
    return manifest


def archive_legacy_ledger(stamp: str | None = None, *, mode: str | None = None) -> dict[str, Any]:
    """Copy the legacy paper ledger into an immutable historical book.

    The archived copy is chmod 444. The originals stay in place and writable:
    dashboards, history readers and audit tests copy them into throwaway roots,
    and a read-only source mode would propagate into those copies. The freeze is
    enforced instead by stopping the legacy controller, by the ctl start guard
    and by the OPS alert that fires if it ever runs after the cutover.

    Legacy trades are never reassigned to timeframes.
    """
    stamp = stamp or stamp_now()
    archive_dir = ROOT / "data" / "archive" / f"legacy_global_paper_ledger_{stamp}"
    archive_dir.mkdir(parents=True, exist_ok=True)
    archived: list[str] = []
    immutable: list[str] = []
    for name in LEGACY_LEDGER_FILES:
        source = LEGACY_PAPER_DIR / name
        for path in (source, source.with_suffix(source.suffix + ".meta.json")):
            if not path.is_file():
                continue
            target = archive_dir / path.name
            shutil.copy2(path, target)
            os.chmod(target, 0o444)
            archived.append(path.name)
            immutable.append(str(target.relative_to(ROOT)))
    payload = {
        "generated_at": utc_now(),
        "legacy_ledger_state": "ARCHIVED_READ_ONLY",
        "legacy_mode_at_cutover": mode or legacy_ledger_mode().get("mode"),
        "archive_dir": str(archive_dir.relative_to(ROOT)),
        "archived_files": archived,
        "immutable_archive_paths": immutable,
        "source_paths": [
            str((LEGACY_PAPER_DIR / name).relative_to(ROOT))
            for name in LEGACY_LEDGER_FILES
            if (LEGACY_PAPER_DIR / name).is_file()
        ],
        "source_write_freeze_enforced_by": [
            "legacy_controller_stopped_at_cutover",
            "ctl_start_guard_after_activation",
            "ops_alert_LEGACY_PAPER_CONTROLLER_RUNNING_AFTER_CUTOVER",
        ],
        "history_reassigned_to_timeframes": False,
        "legacy_book_role": "READ_ONLY_HISTORICAL_BOOK",
    }
    atomic_write_json(LEGACY_MIGRATION_PATH, payload)
    return payload


def restore_legacy_writable(*, names: tuple[str, ...] = LEGACY_LEDGER_FILES) -> list[str]:
    restored: list[str] = []
    for name in names:
        source = LEGACY_PAPER_DIR / name
        if not source.is_file():
            continue
        os.chmod(source, 0o644)
        restored.append(str(source.relative_to(ROOT)))
    return restored


def write_activation_record(
    *,
    stamp: str,
    activation_timestamp: str,
    gates: dict[str, Any],
    backup_manifest: dict[str, Any],
    legacy_migration: dict[str, Any],
    processes: dict[str, Any],
) -> dict[str, Any]:
    paths = CommandBusPaths.production()
    payload = {
        "generated_at": utc_now(),
        "stage": "S4_1_PRODUCTION_ACTIVATION",
        "stamp": stamp,
        "activation_timestamp": activation_timestamp,
        "schema_version": "s4_1_activation_v1",
        "manager": {
            "command_memory": str(paths.memory.relative_to(ROOT)),
            "latest_snapshot": str(paths.latest.relative_to(ROOT)),
            "portfolio_summary": str(paths.portfolio_summary.relative_to(ROOT)),
        },
        "supported_timeframes": ["M15", "M30", "H1", "H4"],
        "d1_trader": False,
        "gates": gates,
        "backup_manifest": {
            "path": backup_manifest.get("manifest_path"),
            "file_count": backup_manifest.get("file_count"),
        },
        "legacy_migration": legacy_migration,
        "processes": processes,
        "paper_only": True,
        "real_execution": False,
        "exchange_calls": 0,
    }
    atomic_write_json(ACTIVATION_PATH, payload)
    atomic_write_json(RESEARCH / f"s4_1_activation_{stamp}.json", payload)
    return payload


def preservation_snapshot(stamp: str | None = None, *, write: bool = True) -> dict[str, Any]:
    stamp = stamp or stamp_now()
    visual = {rel: sha256_of(ROOT / rel) for rel in VISUAL_INVARIANT_FILES}
    datasets: dict[str, Any] = {}
    for rel in SEMANTIC_INVARIANT_DATASETS:
        path = ROOT / rel
        entry: dict[str, Any] = {"exists": path.exists(), "sha256": sha256_of(path)}
        if path.exists() and path.suffix == ".parquet":
            try:
                entry["rows"] = int(len(pd.read_parquet(path, columns=None)))
            except Exception as exc:
                entry["rows_error"] = str(exc)
        datasets[rel] = entry
    payload = {
        "generated_at": utc_now(),
        "stage": "S4_1_PRESERVATION",
        "stamp": stamp,
        "visual_invariant_files": visual,
        "semantic_invariant_datasets": datasets,
        "environment": {
            "BTC_ML_CONTINUATION_PROGRESSION": os.environ.get("BTC_ML_CONTINUATION_PROGRESSION", "0"),
            "PRICE_GATE": os.environ.get("PRICE_GATE", "OFF"),
        },
        "dashboard_redesign": False,
        "css_theme_changed": False,
    }
    if write:
        atomic_write_json(RESEARCH / f"s4_1_preservation_{stamp}.json", payload)
    return payload
