"""Market-state and trading-state responsibility matrices (Phase 1 audit artifacts)."""

from __future__ import annotations

MARKET_STATE_MATRIX = [
    {
        "responsibility": "structural_regime",
        "current_owner": "cognitive_market_state + auction episode",
        "artifact": "data/cognition/cognitive_market_state_memory.parquet",
        "field": "cognitive_market_state / state_status",
        "freshness": "live tip (context chain)",
        "consumer": "final_market_context_memory",
        "classification": "PARTIAL",
        "notes": "BALANCE/DEVELOPING ontology ≠ legacy NEUTRAL/REVERSAL market_state",
    },
    {
        "responsibility": "directional_bias",
        "current_owner": "final context / cognitive state_direction",
        "artifact": "data/cognition/final_market_context_memory.parquet",
        "field": "market_context (LONG/SHORT/OBSERVE); cognitive state_direction",
        "freshness": "live tip",
        "consumer": "context_decision_log; timeframe_manager",
        "classification": "PARTIAL",
        "notes": "Context enum replaces market_bias; not identical trader_read mapping",
    },
    {
        "responsibility": "confidence",
        "current_owner": "decision log (often unavailable)",
        "artifact": "data/live/context_decision_log.parquet",
        "field": "confidence / confidence_available",
        "freshness": "live tip; frequently NO_CONFIDENCE_SOURCE_AVAILABLE",
        "consumer": "paper signal eligibility",
        "classification": "PARTIAL",
        "notes": "Legacy market_state_confidence not produced",
    },
    {
        "responsibility": "transition_type",
        "current_owner": "lifecycle",
        "artifact": "data/cognition/market_context_lifecycle_memory.parquet",
        "field": "transition_reason / lifecycle_state",
        "freshness": "live tip",
        "consumer": "context_decision_log",
        "classification": "PARTIAL",
        "notes": "Lifecycle transitions ≠ legacy transition_type/class/hysteresis",
    },
    {
        "responsibility": "continuation_reversal_interpretation",
        "current_owner": "auction episode + volume response",
        "artifact": "data/cognition/auction_episode_memory.parquet",
        "field": "auction_location / episode class; volume_response continuation_quality",
        "freshness": "mixed (response may carry stale localized_behavior)",
        "consumer": "cognitive / final context builders",
        "classification": "PARTIAL",
        "notes": "Distributed; no single rule_id lineage",
    },
    {
        "responsibility": "rule_lineage",
        "current_owner": "none",
        "artifact": None,
        "field": None,
        "freshness": None,
        "consumer": None,
        "classification": "MISSING",
        "notes": "Legacy rule_id / rule_description / mapping_inputs JSON absent",
    },
    {
        "responsibility": "state_persistence",
        "current_owner": "lifecycle",
        "artifact": "data/cognition/market_context_lifecycle_memory.parquet",
        "field": "active_context_age_bars / state_age_minutes",
        "freshness": "live tip",
        "consumer": "decision log",
        "classification": "PRESENT",
        "notes": "Episode persistence tracked",
    },
    {
        "responsibility": "state_invalidation",
        "current_owner": "lifecycle + decision log",
        "artifact": "market_context_lifecycle_memory / context_decision_log",
        "field": "invalidation_type / context_end_event / observe_block_reason",
        "freshness": "live tip",
        "consumer": "manager commands (via context state)",
        "classification": "PRESENT",
        "notes": "Connected via lifecycle_episode_id inside cognition plane only",
    },
]

TRADING_STATE_MATRIX = [
    {
        "responsibility": "execution_posture",
        "current_owner": "decision log + manager command",
        "artifact": "context_decision_log; timeframe_command_memory",
        "field": "paper_action_candidate; intent / timeframe_state",
        "freshness": "live tip",
        "consumer": "timeframe traders",
        "classification": "PARTIAL",
        "notes": "No legacy trading_state enum (REVERSAL_WATCH etc.)",
    },
    {
        "responsibility": "entry_eligibility",
        "current_owner": "decision log",
        "artifact": "data/live/context_decision_log.parquet",
        "field": "signal_eligibility_status / action_allowed",
        "freshness": "live tip",
        "consumer": "manager (indirect via context)",
        "classification": "PRESENT",
        "notes": "ELIGIBLE_* / BLOCKED_* statuses",
    },
    {
        "responsibility": "action_allowed",
        "current_owner": "final context + decision log + command",
        "artifact": "final_market_context_memory; context_decision_log; command_memory",
        "field": "action_allowed",
        "freshness": "live tip",
        "consumer": "manager / traders",
        "classification": "PRESENT",
        "notes": "Consistent false under OBSERVE",
    },
    {
        "responsibility": "no_trade_reason",
        "current_owner": "decision log",
        "artifact": "context_decision_log",
        "field": "observe_block_reason / signal_block_reasons / paper_action_candidate",
        "freshness": "live tip",
        "consumer": "research / OPS research ribbon",
        "classification": "PRESENT",
    },
    {
        "responsibility": "stand_aside_reason",
        "current_owner": "none (mapped to OBSERVE)",
        "artifact": "context_decision_log",
        "field": "OBSERVE / NO_TRADE_OBSERVE",
        "freshness": "live tip",
        "consumer": "manager NO_ACTION",
        "classification": "PARTIAL",
        "notes": "STAND_ASIDE posture not first-class",
    },
    {
        "responsibility": "decision_state",
        "current_owner": "decision log",
        "artifact": "context_decision_log",
        "field": "decision_id + payload",
        "freshness": "live tip",
        "consumer": "lineage candidate",
        "classification": "PRESENT",
    },
    {
        "responsibility": "command_state",
        "current_owner": "timeframe manager",
        "artifact": "data/trading/manager/timeframe_command_memory.parquet",
        "field": "command_id / intent / reason_codes",
        "freshness": "live tip",
        "consumer": "timeframe traders",
        "classification": "PRESENT",
        "notes": "No decision_id FK on commands — lineage gap",
    },
    {
        "responsibility": "command_consumption",
        "current_owner": "timeframe traders",
        "artifact": "timeframe_traders/*/controller_state.json + signals/orders",
        "field": "processed_command_ids / command_id",
        "freshness": "live tip",
        "consumer": "orders/fills/positions/trades",
        "classification": "PRESENT",
        "notes": "Closed spine via command_id; disconnected from decision_id",
    },
]
