"""Observe-only economic quality & correlation research shadow."""

from __future__ import annotations

FIELD_NOT_AVAILABLE = "FIELD_NOT_AVAILABLE"
WRITE_BOUNDARY_VIOLATION = "SHADOW_EQCORR_WRITE_BOUNDARY_VIOLATION"
BASELINE_DIVERGENCE = "SHADOW_EQCORR_BASELINE_DIVERGENCE"
LOOKAHEAD_VIOLATION = "SHADOW_EQCORR_LOOKAHEAD_VIOLATION"
SOURCE_EPOCH_MISMATCH = "SHADOW_EQCORR1_SOURCE_EPOCH_MISMATCH"
STATUS_ACTIVE = "SHADOW_EQCORR1_OBSERVE_ONLY_ACTIVE"
STATUS_ENRICHMENT_ACTIVE = "SHADOW_EQCORR1_1_CAUSAL_FEATURE_ENRICHMENT_ACTIVE"
STATUS_ENRICHMENT_PARTIAL = "SHADOW_EQCORR1_1_ACTIVE_WITH_EXPLICIT_MISSING_FEATURES"
STATUS_ENRICHMENT_LOOKAHEAD = "SHADOW_EQCORR1_1_LOOKAHEAD_VIOLATION"
STATUS_ENRICHMENT_AMBIGUOUS = "SHADOW_EQCORR1_1_TIMESTAMP_SEMANTICS_AMBIGUOUS"
STATUS_ENRICHMENT_BASELINE = "SHADOW_EQCORR1_1_BASELINE_DIVERGENCE"
STATUS_ENRICHMENT_WRITE = "SHADOW_EQCORR1_1_WRITE_BOUNDARY_VIOLATION"

EXPECTED_EPOCH = "PER_TF_EQUITY_1PCT_V1_20260729_181431"
EXPECTED_PARENT_FP = "a6a916a767c6cfe83e9eb4581103d422bfc1adad6a56dfbf8f867930c129cb5a"
EXPECTED_ACTIVE_FP = "ca13177674222de7991dc26688ee2f91e018e5728a1660af6dc81c326acf7129"

TACTICAL = frozenset({"M15", "M30"})
STRUCTURAL = frozenset({"H1", "H4"})
TIMEFRAMES = ("M15", "M30", "H1", "H4")

POLICY_IDS = (
    "BASELINE_ALL_ELIGIBLE",
    "MAX_1_SAME_DIRECTION",
    "MAX_2_SAME_DIRECTION",
    "MAX_3_SAME_DIRECTION",
    "ONE_TACTICAL_ONE_STRUCTURAL",
    "PROGRESSIVE_RISK_REDUCTION",
    "DIRECTION_RISK_CAP_025_BLOCK",
    "DIRECTION_RISK_CAP_025_REDUCE",
    "DIRECTION_RISK_CAP_050_BLOCK",
    "DIRECTION_RISK_CAP_050_REDUCE",
    "DIRECTION_RISK_CAP_075_BLOCK",
    "DIRECTION_RISK_CAP_075_REDUCE",
    "DIRECTION_RISK_CAP_100_BLOCK",
    "DIRECTION_RISK_CAP_100_REDUCE",
    "M15_ONLY",
    "M30_ONLY",
    "H1_ONLY",
    "H4_ONLY",
)
